#!/usr/bin/env node
var debug = require('debug')('strife');
var app = require('./app');
var config = require('./config');

app.set('port',  process.env.PORT || config.port);

var server = app.listen(app.get('port'),function() {
  console.log('Server listening on port ' + server.address().port);
});
require('./webViewServer').createServer(server);
